{% set name = "bullet" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b2457214fc54932a6bfba62c9e4b781840aed799734187e147df33a83b472b7c

build:
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pybullet

about:
  home:  http://bulletphysics.org
  license: zlib
  license_file: LICENSE.txt
  summary: Bullet Physics SDK real-time collision detection
    and multi-physics simulation for VR, games, visual effects, robotics, machine learning etc.

extra:
  recipe-maintainers:
    - xantares
