{% set version = "3.07" %}

package:
  name: bullet
  version: {{ version }}

source:
  fn: bullet3-{{ version }}.tar.gz
  url: https://github.com/bulletphysics/bullet3/archive/{{ version }}.tar.gz
  sha256: 068ecf8acbf256d3976eebee75d7d6f5af16c049f10f6b2d8ba28bb638bef3b0
  patches:
    # linux: examples/ThirdPartyLibs/openvr/bin/linux64/libopenvr_api.so: undefined reference to `memcpy@GLIBC_2.14'
    - disable-sharedmemory.patch

build:
  number: 0
  skip: true  # [ppc64le]

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pybullet

about:
  home: http://bulletphysics.org
  license: Zlib
  license_file: LICENSE.txt
  summary: Bullet Physics SDK real-time collision detection and multi-physics simulation for VR, games, visual effects, robotics, machine learning etc.

extra:
  recipe-maintainers:
    - xantares
