{% set pypi_name = "pybullet" %}
{% set name = "bullet" %}
{% set version = "3.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: df1951aea5917d03870977a416fb2cd8703dee1a21618b6a3a464143e291afa7

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
    - setuptools
    - numpy >=1.11
    - wheel
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pybullet

about:
  home:  http://bulletphysics.org
  license: Zlib
  license_file: LICENSE.txt
  summary: Bullet Physics SDK real-time collision detection
    and multi-physics simulation for VR, games, visual effects, robotics, machine learning etc.

extra:
  recipe-maintainers:
    - xantares
    - gonzalocasas
